import { expect, test } from '@playwright/test'

for (const viewport of [{ width: 1440, height: 900 }, { width: 390, height: 844 }]) {
  test(`sender and time align without overlapping controls at ${viewport.width}px`, async ({ page }) => {
    await page.setViewportSize(viewport)
    await page.goto('/')
    if (viewport.width < 1200) await page.getByRole('tab', { name: '消息', exact: true }).click()
    const sender = await page.getByLabel('消息 1 发送人', { exact: true }).boundingBox()
    const time = await page.getByLabel('消息 1 时间', { exact: true }).boundingBox()
    const type = await page.getByLabel('消息 1 类型', { exact: true }).boundingBox()
    const direction = await page.getByLabel('消息 1 方向', { exact: true }).boundingBox()
    expect(sender).not.toBeNull()
    expect(time).not.toBeNull()
    expect(Math.abs(sender!.width - time!.width)).toBeLessThan(1)
    expect(Math.abs(sender!.x - time!.x)).toBeLessThan(1)
    expect(type!.x + type!.width).toBeLessThanOrEqual(direction!.x - 2)
    const visibility = await page.getByLabel('消息 1 时间显示', { exact: true }).boundingBox()
    const insert = await page.getByRole('button', { name: '在消息 1 下方插入', exact: true }).boundingBox()
    expect(visibility!.x + visibility!.width).toBeLessThanOrEqual(insert!.x - 2)
    await page.getByLabel('消息 1 类型', { exact: true }).selectOption('recall')
    const recallSender = await page.getByLabel('消息 1 发送人', { exact: true }).boundingBox()
    const recallTime = await page.getByLabel('消息 1 时间', { exact: true }).boundingBox()
    expect(Math.abs(recallSender!.width - recallTime!.width)).toBeLessThan(1)
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(viewport.width)
  })
}

test('insertion, selection cancellation and clearing with undo work in the browser', async ({ page }) => {
  await page.goto('/')
  const rows = page.getByRole('article', { name: /^消息 \d+$/ })
  const count = await rows.count()
  await page.getByRole('button', { name: '在消息 1 下方插入', exact: true }).click()
  await expect(rows).toHaveCount(count + 1)
  await expect(page.getByLabel('消息 2 内容', { exact: true })).toHaveValue('')
  const input = page.getByLabel('消息 2 内容', { exact: true })
  const sender = page.getByLabel('消息 2 发送人', { exact: true })
  const original = await sender.inputValue()
  await input.focus()
  await page.keyboard.press('Tab')
  await expect(input).toBeFocused()
  expect(await sender.inputValue()).not.toBe(original)
  await page.keyboard.press('Shift+Tab')
  await expect(sender).toHaveValue(original)
  await page.getByRole('button', { name: '多选消息', exact: true }).click()
  await page.getByLabel('选择消息 2', { exact: true }).check()
  await page.getByRole('button', { name: '删除选中（1）', exact: true }).click()
  const deleteDialog = page.getByRole('dialog', { name: '删除选中的 1 条消息？', exact: true })
  await expect(deleteDialog).toContainText('删除后可通过撤销恢复')
  await deleteDialog.getByRole('button', { name: '取消', exact: true }).click()
  await expect(rows).toHaveCount(count + 1)
  await page.getByRole('button', { name: '删除选中（1）', exact: true }).click()
  await page.getByRole('dialog', { name: '删除选中的 1 条消息？', exact: true })
    .getByRole('button', { name: '确认删除 1 条消息', exact: true }).click()
  await expect(rows).toHaveCount(count)
  await page.getByRole('button', { name: '清空消息', exact: true }).click()
  const clearDialog = page.getByRole('dialog', { name: `清空全部 ${count} 条消息？`, exact: true })
  await expect(clearDialog).toContainText('清空后可通过撤销恢复')
  await clearDialog.getByRole('button', { name: '确认清空消息', exact: true }).click()
  await expect(rows).toHaveCount(0)
  await page.getByRole('button', { name: /^撤销/ }).click()
  await expect(rows).toHaveCount(count)
})
