import type { ChatDraft } from './chatTypes'
import { createMessage } from './messageFactory'

export const SAMPLE_DRAFT: ChatDraft = {
  schemaVersion: 3,
  conversationType: 'group',
  groupMemberCount: null,
  showGroupNicknames: true,
  title: '仙女驻凡大使馆',
  theme: 'dark',
  showStatusBar: true,
  statusTime: '10:35',
  batteryPercent: 85,
  showSilentIcon: true,
  followSystemTime: false,
  batteryCharging: false,
  showDoNotDisturb: false,
  earpieceMode: false,
  chatUnreadCount: 0,
  networkType: 'wifi',
  signalStrength: 4,
  outputMode: 'screen',
  captureStartMessageId: null,
  captureEndMessageId: null,
  screenScrollTop: 0,
  outputWidth: 430,
  outputHeight: 932,
  exportScale: 3,
  showInputBar: true,
  inputBarMode: 'text',
  inputDraft: '',
  showHomeIndicator: false,
  timeDisplayMode: 'smart',
  wallpaper: null,
  participants: [
    { id: 'self', name: '小美', avatarDataUrl: null, isSelf: true },
    { id: 'p2', name: '阿花', avatarDataUrl: null, isSelf: false },
    { id: 'p3', name: '阿强', avatarDataUrl: null, isSelf: false },
    { id: 'p4', name: '小雨', avatarDataUrl: null, isSelf: false },
  ],
  messages: [
    { id: 'm1', participantId: 'self', kind: 'text', text: '姐妹们！', showReeditLink: false, media: null, voiceUnread: false, call: null, side: 'auto', sentAt: '2026-08-27T10:00:00+08:00', timeVisibility: 'hide' },
    { id: 'm2', participantId: 'self', kind: 'text', text: '我老公让我全职带娃，每个月给我两万！！！', showReeditLink: false, media: null, voiceUnread: false, call: null, side: 'auto', sentAt: '2026-08-27T10:01:00+08:00', timeVisibility: 'auto' },
    { id: 'm3', participantId: 'p2', kind: 'text', text: '两万！', showReeditLink: false, media: null, voiceUnread: false, call: null, side: 'auto', sentAt: '2026-08-27T10:02:00+08:00', timeVisibility: 'auto' },
    { id: 'm4', participantId: 'p2', kind: 'text', text: '他一个月工资多少啊', showReeditLink: false, media: null, voiceUnread: false, call: null, side: 'auto', sentAt: '2026-08-27T10:03:00+08:00', timeVisibility: 'auto' },
    { id: 'm5', participantId: 'self', kind: 'text', text: '他月薪四万五', showReeditLink: false, media: null, voiceUnread: false, call: null, side: 'auto', sentAt: '2026-08-27T10:04:00+08:00', timeVisibility: 'auto' },
    { id: 'm6', participantId: 'self', kind: 'text', text: '自己留一半', showReeditLink: false, media: null, voiceUnread: false, call: null, side: 'auto', sentAt: '2026-08-27T10:05:00+08:00', timeVisibility: 'auto' },
    { id: 'm7', participantId: 'p2', kind: 'text', text: '那一半留着干啥，口气真大', showReeditLink: false, media: null, voiceUnread: false, call: null, side: 'auto', sentAt: '2026-08-27T10:12:00+08:00', timeVisibility: 'auto' },
    { id: 'm8', participantId: 'p3', kind: 'text', text: '和着他要用一半工资买断你全部人生😂😂😂', showReeditLink: false, media: null, voiceUnread: false, call: null, side: 'auto', sentAt: '2026-08-27T10:13:00+08:00', timeVisibility: 'auto' },
    { id: 'm9', participantId: 'p4', kind: 'text', text: '这算盘打的我在隔壁城市都听到了🐱', showReeditLink: false, media: null, voiceUnread: false, call: null, side: 'auto', sentAt: '2026-08-27T10:14:00+08:00', timeVisibility: 'auto' },
  ].map(message => createMessage(message.participantId, { ...message, kind: 'text', side: 'auto', timeVisibility: message.timeVisibility === 'hide' ? 'hide' : 'auto' })),
}
